"use client";

import Link from "next/link";
import { ArrowLeft, Award, BookOpen, ShieldCheck, Heart } from "lucide-react";

export default function AboutPage() {
  return (
    <div className="flex flex-col min-h-screen bg-bg-base text-text selection:bg-primary/20 font-sans">
      {/* Navbar */}
      <header className="glass-panel border-b border-border/40 px-6 py-4 flex items-center justify-between">
        <Link href="/" className="flex items-center space-x-2 cursor-pointer">
          <img src="/logo.png" alt="ATSLift Logo" className="w-8 h-8 rounded-md object-contain logo-rotated" />
          <span className="font-bold text-lg tracking-tight text-text">
            ATS<span className="text-primary font-medium font-serif italic">Lift</span>
          </span>
        </Link>
        <Link
          href="/"
          className="text-xs font-bold text-primary hover:underline flex items-center space-x-1"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Back to Home</span>
        </Link>
      </header>

      {/* Main Section */}
      <main className="max-w-3xl mx-auto w-full px-6 py-16 space-y-12 flex-1">
        {/* Title */}
        <div className="space-y-4 text-center">
          <h1 className="text-4xl md:text-6xl font-serif tracking-tight leading-[1.1]">
            Our Story & <span className="text-primary italic font-normal">Mission</span>
          </h1>
          <p className="text-sm md:text-base text-text-muted max-w-lg mx-auto leading-relaxed font-semibold">
            ATSLift was born out of placement room frustration. Built by engineering students, for engineering students.
          </p>
        </div>

        {/* Narrative Cards */}
        <div className="grid grid-cols-1 gap-8 pt-6">
          <div className="bg-surface border border-border rounded-2xl p-6 md:p-8 space-y-4 shadow-xs">
            <div className="w-10 h-10 rounded-full bg-primary/10 border border-primary/20 flex items-center justify-center text-primary">
              <BookOpen className="w-5 h-5" />
            </div>
            <h2 className="text-xl font-bold font-sans">The Placement Dilemma</h2>
            <p className="text-sm text-text-muted leading-relaxed font-medium">
              During college placement seasons (across campuses like VIT, NITs, and BITS), we observed a recurring tragedy: highly competent developers with outstanding projects were failing to clear the initial resume screening rounds.
            </p>
            <p className="text-sm text-text-muted leading-relaxed font-medium">
              We realized that standard visual templates generated by online tools use complex graphics, non-standard headings, or table layouts. Standard Applicant Tracking Systems (ATS) completely fail to parse these visual layouts, leading to automated rejections before a human recruiter even opens the file.
            </p>
          </div>

          <div className="bg-surface border border-border rounded-2xl p-6 md:p-8 space-y-4 shadow-xs">
            <div className="w-10 h-10 rounded-full bg-success/10 border border-success/20 flex items-center justify-center text-success">
              <ShieldCheck className="w-5 h-5" />
            </div>
            <h2 className="text-xl font-bold font-sans">Our Approach: ATS-Safe, Bullet-First</h2>
            <p className="text-sm text-text-muted leading-relaxed font-medium">
              Instead of locking you into proprietary resume editors that force you to buy expensive subscriptions, ATSLift is built to do one thing flawlessly: <strong>optimize your written content</strong>.
            </p>
            <p className="text-sm text-text-muted leading-relaxed font-medium">
              We translate raw details (like college CGPA, technology lists, and project summaries) into quantified, metrics-focused bullet points utilizing industry-specific action verbs. Our outputs are formatted as clean, standard plain text that can be copied directly into clean, single-column Microsoft Word or Overleaf LaTeX templates.
            </p>
          </div>

          <div className="bg-surface border border-border rounded-2xl p-6 md:p-8 space-y-4 shadow-xs">
            <div className="w-10 h-10 rounded-full bg-primary/10 border border-primary/20 flex items-center justify-center text-primary">
              <Award className="w-5 h-5" />
            </div>
            <h2 className="text-xl font-bold font-sans">Fair, Frictionless Monetization</h2>
            <p className="text-sm text-text-muted leading-relaxed font-medium">
              Engineering students shouldn&apos;t have to pay massive subscription fees to unlock a resume. We offer a transparent, single-run payment structure:
            </p>
            <ul className="list-disc pl-5 space-y-2 text-xs font-semibold text-text-muted">
              <li><strong>Free Tier:</strong> Basic ATS score check, custom optimization tips, professional summary teaser, and first project bullets preview.</li>
              <li><strong>Paid Tier (₹49):</strong> Instant one-time unlock of the entire resume draft, unlimited clipboard copying, print-optimized PDF outputs, Resend email delivery, and 3 custom regenerations to adjust tone or match specific Job Descriptions.</li>
            </ul>
          </div>
        </div>

        {/* Dedication Block */}
        <div className="text-center pt-8 border-t border-border/40 space-y-2">
          <p className="text-xs text-text-muted font-bold inline-flex items-center space-x-1.5">
            <span>Made with</span>
            <Heart className="w-4 h-4 text-error fill-error animate-pulse" />
            <span>for the Indian SDE campus community.</span>
          </p>
          <p className="text-[10px] text-text-muted font-semibold">
            ATSLift is not affiliated with any particular college or placement system. Built to level the playing field.
          </p>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border/60 bg-surface px-6 py-8 text-center text-xs text-text-muted font-medium">
        <div className="max-w-3xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <span>© {new Date().getFullYear()} ATSLift. All rights reserved.</span>
          <Link href="/" className="hover:text-primary transition-colors">
            Home
          </Link>
        </div>
      </footer>
    </div>
  );
}
